/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "mux_de_control_forzado.v:1" *)
module mux_de_control_forzado_sintetizado(CONTROL, VALID, Tx_Buffer, CLK, OUT);
  (* src = "mux_de_control_forzado.v:7" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  (* src = "mux_de_control_forzado.v:4" *)
  input CLK;
  (* src = "mux_de_control_forzado.v:1" *)
  input [3:0] CONTROL;
  (* src = "mux_de_control_forzado.v:5" *)
  output [7:0] OUT;
  (* src = "mux_de_control_forzado.v:3" *)
  input [7:0] Tx_Buffer;
  (* src = "mux_de_control_forzado.v:2" *)
  input VALID;
  NOT _060_ (
    .A(CONTROL[3]),
    .Y(_001_)
  );
  NOT _061_ (
    .A(CONTROL[1]),
    .Y(_002_)
  );
  NAND _062_ (
    .A(_002_),
    .B(_001_),
    .Y(_003_)
  );
  NOR _063_ (
    .A(_003_),
    .B(CONTROL[2]),
    .Y(_004_)
  );
  NAND _064_ (
    .A(_004_),
    .B(CONTROL[0]),
    .Y(_005_)
  );
  NOT _065_ (
    .A(CONTROL[0]),
    .Y(_006_)
  );
  NOR _066_ (
    .A(CONTROL[2]),
    .B(CONTROL[3]),
    .Y(_007_)
  );
  NAND _067_ (
    .A(_007_),
    .B(CONTROL[0]),
    .Y(_008_)
  );
  NOR _068_ (
    .A(_008_),
    .B(_002_),
    .Y(_009_)
  );
  NOT _069_ (
    .A(CONTROL[2]),
    .Y(_010_)
  );
  NOR _070_ (
    .A(_003_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _071_ (
    .A(_011_),
    .B(_009_),
    .Y(_012_)
  );
  NOR _072_ (
    .A(_012_),
    .B(_006_),
    .Y(_013_)
  );
  NOT _073_ (
    .A(Tx_Buffer[0]),
    .Y(_014_)
  );
  NAND _074_ (
    .A(_002_),
    .B(CONTROL[3]),
    .Y(_015_)
  );
  NOR _075_ (
    .A(_015_),
    .B(CONTROL[2]),
    .Y(_016_)
  );
  NAND _076_ (
    .A(_016_),
    .B(CONTROL[0]),
    .Y(_017_)
  );
  NOR _077_ (
    .A(_017_),
    .B(_014_),
    .Y(_018_)
  );
  NOR _078_ (
    .A(_018_),
    .B(_013_),
    .Y(_019_)
  );
  NAND _079_ (
    .A(_019_),
    .B(_005_),
    .Y(_000_[0])
  );
  NOR _080_ (
    .A(CONTROL[1]),
    .B(_001_),
    .Y(_020_)
  );
  NAND _081_ (
    .A(_020_),
    .B(_010_),
    .Y(_021_)
  );
  NOR _082_ (
    .A(_021_),
    .B(_006_),
    .Y(_022_)
  );
  NAND _083_ (
    .A(_022_),
    .B(Tx_Buffer[1]),
    .Y(_023_)
  );
  NAND _084_ (
    .A(CONTROL[2]),
    .B(CONTROL[1]),
    .Y(_024_)
  );
  NOR _085_ (
    .A(_024_),
    .B(CONTROL[3]),
    .Y(_025_)
  );
  NAND _086_ (
    .A(_025_),
    .B(_006_),
    .Y(_026_)
  );
  NAND _087_ (
    .A(_026_),
    .B(_008_),
    .Y(_027_)
  );
  NOT _088_ (
    .A(_027_),
    .Y(_028_)
  );
  NAND _089_ (
    .A(_028_),
    .B(_023_),
    .Y(_000_[1])
  );
  NAND _090_ (
    .A(_010_),
    .B(_001_),
    .Y(_029_)
  );
  NOR _091_ (
    .A(_029_),
    .B(CONTROL[0]),
    .Y(_030_)
  );
  NOT _092_ (
    .A(_025_),
    .Y(_031_)
  );
  NAND _093_ (
    .A(_016_),
    .B(_006_),
    .Y(_032_)
  );
  NAND _094_ (
    .A(_032_),
    .B(_031_),
    .Y(_033_)
  );
  NOR _095_ (
    .A(_033_),
    .B(_030_),
    .Y(_034_)
  );
  NOR _096_ (
    .A(CONTROL[1]),
    .B(CONTROL[3]),
    .Y(_035_)
  );
  NOT _097_ (
    .A(Tx_Buffer[2]),
    .Y(_036_)
  );
  NOR _098_ (
    .A(_017_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _099_ (
    .A(_037_),
    .B(_035_),
    .Y(_038_)
  );
  NAND _100_ (
    .A(_038_),
    .B(_034_),
    .Y(_000_[2])
  );
  NOR _101_ (
    .A(_029_),
    .B(_006_),
    .Y(_039_)
  );
  NAND _102_ (
    .A(_039_),
    .B(CONTROL[1]),
    .Y(_040_)
  );
  NAND _103_ (
    .A(_035_),
    .B(CONTROL[2]),
    .Y(_041_)
  );
  NAND _104_ (
    .A(_041_),
    .B(_040_),
    .Y(_042_)
  );
  NOT _105_ (
    .A(Tx_Buffer[3]),
    .Y(_043_)
  );
  NOR _106_ (
    .A(_017_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _107_ (
    .A(_044_),
    .B(_042_),
    .Y(_045_)
  );
  NAND _108_ (
    .A(_045_),
    .B(_034_),
    .Y(_000_[3])
  );
  NOT _109_ (
    .A(Tx_Buffer[4]),
    .Y(_046_)
  );
  NAND _110_ (
    .A(_046_),
    .B(CONTROL[0]),
    .Y(_047_)
  );
  NAND _111_ (
    .A(_047_),
    .B(_016_),
    .Y(_048_)
  );
  NAND _112_ (
    .A(_048_),
    .B(CONTROL[3]),
    .Y(_000_[4])
  );
  NOT _113_ (
    .A(Tx_Buffer[5]),
    .Y(_049_)
  );
  NOR _114_ (
    .A(_017_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _115_ (
    .A(_050_),
    .B(_033_),
    .Y(_051_)
  );
  NOR _116_ (
    .A(_013_),
    .B(_004_),
    .Y(_052_)
  );
  NAND _117_ (
    .A(_052_),
    .B(_051_),
    .Y(_000_[5])
  );
  NAND _118_ (
    .A(_022_),
    .B(Tx_Buffer[6]),
    .Y(_053_)
  );
  NAND _119_ (
    .A(_032_),
    .B(_041_),
    .Y(_054_)
  );
  NOR _120_ (
    .A(_054_),
    .B(_027_),
    .Y(_055_)
  );
  NAND _121_ (
    .A(_055_),
    .B(_053_),
    .Y(_000_[6])
  );
  NOT _122_ (
    .A(_026_),
    .Y(_056_)
  );
  NOT _123_ (
    .A(Tx_Buffer[7]),
    .Y(_057_)
  );
  NOR _124_ (
    .A(_017_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _125_ (
    .A(_058_),
    .B(_056_),
    .Y(_059_)
  );
  NAND _126_ (
    .A(_059_),
    .B(_052_),
    .Y(_000_[7])
  );
  DFF _127_ (
    .C(CLK),
    .D(_000_[0]),
    .Q(OUT[0])
  );
  DFF _128_ (
    .C(CLK),
    .D(_000_[1]),
    .Q(OUT[1])
  );
  DFF _129_ (
    .C(CLK),
    .D(_000_[2]),
    .Q(OUT[2])
  );
  DFF _130_ (
    .C(CLK),
    .D(_000_[3]),
    .Q(OUT[3])
  );
  DFF _131_ (
    .C(CLK),
    .D(_000_[4]),
    .Q(OUT[4])
  );
  DFF _132_ (
    .C(CLK),
    .D(_000_[5]),
    .Q(OUT[5])
  );
  DFF _133_ (
    .C(CLK),
    .D(_000_[6]),
    .Q(OUT[6])
  );
  DFF _134_ (
    .C(CLK),
    .D(_000_[7]),
    .Q(OUT[7])
  );
endmodule
