all:
	g++ -std=c++11 -pthread -o dft_parallel+ dft_parallel.cpp

clean:
	rm dft_parallel+

run:
	./dft_parallel+ 10 4
	./dft_parallel+ 20 4
	./dft_parallel+ 30 4
	./dft_parallel+ 40 4
	./dft_parallel+ 50 4
	./dft_parallel+ 60 4
	./dft_parallel+ 70 4
	./dft_parallel+ 80 4
	./dft_parallel+ 90 4
	./dft_parallel+ 100 4
