/* Generated by Yosys 0.5+ (git sha1 f13e387, gcc 5.3.1-8ubuntu2 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "FSM.v:2" *)
module FSM(clk, reset, init, almost_full, almost_empty, empty_Fifo, no_empty_Fifo, Fifo_overflow, error_full, pausa, continua, data_Fifo);
  (* src = "FSM.v:19" *)
  wire [3:0] _00_;
  (* src = "FSM.v:19" *)
  wire [3:0] _01_;
  (* src = "FSM.v:19" *)
  wire [3:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "FSM.v:2" *)
  input Fifo_overflow;
  (* src = "FSM.v:2" *)
  input almost_empty;
  (* src = "FSM.v:2" *)
  input almost_full;
  (* src = "FSM.v:2" *)
  input clk;
  (* src = "FSM.v:3" *)
  output [3:0] continua;
  (* src = "FSM.v:4" *)
  input [7:0] data_Fifo;
  (* src = "FSM.v:2" *)
  input empty_Fifo;
  (* src = "FSM.v:3" *)
  output [3:0] error_full;
  (* src = "FSM.v:2" *)
  input init;
  (* src = "FSM.v:2" *)
  input no_empty_Fifo;
  (* src = "FSM.v:3" *)
  output [3:0] pausa;
  (* src = "FSM.v:2" *)
  input reset;
  NOT _17_ (
    .A(error_full[0]),
    .Y(_03_)
  );
  NOT _18_ (
    .A(init),
    .Y(_04_)
  );
  NOR _19_ (
    .A(reset),
    .B(_04_),
    .Y(_05_)
  );
  NOR _20_ (
    .A(_05_),
    .B(_03_),
    .Y(_01_[0])
  );
  NOT _21_ (
    .A(error_full[1]),
    .Y(_06_)
  );
  NOR _22_ (
    .A(_05_),
    .B(_06_),
    .Y(_01_[1])
  );
  NOT _23_ (
    .A(error_full[2]),
    .Y(_07_)
  );
  NOR _24_ (
    .A(_05_),
    .B(_07_),
    .Y(_01_[2])
  );
  NOT _25_ (
    .A(error_full[3]),
    .Y(_08_)
  );
  NOR _26_ (
    .A(_05_),
    .B(_08_),
    .Y(_01_[3])
  );
  NOT _27_ (
    .A(pausa[0]),
    .Y(_09_)
  );
  NOR _28_ (
    .A(_05_),
    .B(_09_),
    .Y(_02_[0])
  );
  NOT _29_ (
    .A(pausa[1]),
    .Y(_10_)
  );
  NOR _30_ (
    .A(_05_),
    .B(_10_),
    .Y(_02_[1])
  );
  NOT _31_ (
    .A(pausa[2]),
    .Y(_11_)
  );
  NOR _32_ (
    .A(_05_),
    .B(_11_),
    .Y(_02_[2])
  );
  NOT _33_ (
    .A(pausa[3]),
    .Y(_12_)
  );
  NOR _34_ (
    .A(_05_),
    .B(_12_),
    .Y(_02_[3])
  );
  NOT _35_ (
    .A(continua[0]),
    .Y(_13_)
  );
  NOR _36_ (
    .A(_05_),
    .B(_13_),
    .Y(_00_[0])
  );
  NOT _37_ (
    .A(continua[1]),
    .Y(_14_)
  );
  NOR _38_ (
    .A(_05_),
    .B(_14_),
    .Y(_00_[1])
  );
  NOT _39_ (
    .A(continua[2]),
    .Y(_15_)
  );
  NOR _40_ (
    .A(_05_),
    .B(_15_),
    .Y(_00_[2])
  );
  NOT _41_ (
    .A(continua[3]),
    .Y(_16_)
  );
  NOR _42_ (
    .A(_05_),
    .B(_16_),
    .Y(_00_[3])
  );
  DFF _43_ (
    .C(clk),
    .D(_01_[0]),
    .Q(error_full[0])
  );
  DFF _44_ (
    .C(clk),
    .D(_01_[1]),
    .Q(error_full[1])
  );
  DFF _45_ (
    .C(clk),
    .D(_01_[2]),
    .Q(error_full[2])
  );
  DFF _46_ (
    .C(clk),
    .D(_01_[3]),
    .Q(error_full[3])
  );
  DFF _47_ (
    .C(clk),
    .D(_02_[0]),
    .Q(pausa[0])
  );
  DFF _48_ (
    .C(clk),
    .D(_02_[1]),
    .Q(pausa[1])
  );
  DFF _49_ (
    .C(clk),
    .D(_02_[2]),
    .Q(pausa[2])
  );
  DFF _50_ (
    .C(clk),
    .D(_02_[3]),
    .Q(pausa[3])
  );
  DFF _51_ (
    .C(clk),
    .D(_00_[0]),
    .Q(continua[0])
  );
  DFF _52_ (
    .C(clk),
    .D(_00_[1]),
    .Q(continua[1])
  );
  DFF _53_ (
    .C(clk),
    .D(_00_[2]),
    .Q(continua[2])
  );
  DFF _54_ (
    .C(clk),
    .D(_00_[3]),
    .Q(continua[3])
  );
endmodule
